# Generated by Django 5.0.2 on 2026-03-17 06:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(editable=False, max_length=20, unique=True)),
                ("client_name", models.CharField(max_length=120)),
                ("contact_person", models.CharField(max_length=120)),
                ("phone_number", models.CharField(blank=True, max_length=25)),
                (
                    "phone_digits",
                    models.CharField(
                        blank=True, db_index=True, editable=False, max_length=20
                    ),
                ),
                (
                    "name_key",
                    models.CharField(
                        blank=True, db_index=True, editable=False, max_length=120
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.CharField(blank=True, max_length=180)),
            ],
            options={
                "ordering": ("client_name", "code"),
            },
        ),
        migrations.CreateModel(
            name="DocumentSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("CLIENT", "Client"),
                            ("QUOTATION", "Quotation"),
                            ("ORDER", "Order"),
                        ],
                        max_length=20,
                    ),
                ),
                ("year_suffix", models.CharField(blank=True, max_length=2)),
                ("last_value", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ("key", "year_suffix"),
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Confirmado", "Confirmado")],
                        default="Confirmado",
                        max_length=20,
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ("-confirmed_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quotation_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("CONFIRMED", "Confirmed")],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("client_name", models.CharField(max_length=120)),
                ("phone_number", models.CharField(blank=True, max_length=25)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=180)),
                ("neighborhood", models.CharField(blank=True, max_length=120)),
                ("reference", models.CharField(blank=True, max_length=220)),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("event_date", models.DateField(blank=True, null=True)),
                ("collection_date", models.DateField(blank=True, null=True)),
                (
                    "freight",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "security_deposit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_estimated",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="QuotationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("equipment", models.CharField(max_length=120)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.AddConstraint(
            model_name="documentsequence",
            constraint=models.UniqueConstraint(
                fields=("key", "year_suffix"), name="unique_document_sequence_per_year"
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotations",
                to="api.client",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="quotation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order",
                to="api.quotation",
            ),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="quotation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipment_items",
                to="api.quotation",
            ),
        ),
    ]
