# Generated by Django 5.0.2 on 2026-03-18 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_inventoryproduct"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="billing_status",
            field=models.CharField(
                choices=[
                    ("AL_CORRIENTE", "Al corriente"),
                    ("POR_COBRAR", "Por cobrar"),
                    ("COBRADO", "Cobrado"),
                ],
                default="AL_CORRIENTE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="operational_status",
            field=models.CharField(
                choices=[
                    ("PROGRAMADA", "Programada"),
                    ("ENTREGADO", "Entregado"),
                    ("POR_RECOGER", "Por recoger"),
                    ("CLIENTE_ENTREGA", "Cliente entrega"),
                    ("RECOGIDO", "Recogido"),
                ],
                default="PROGRAMADA",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="OrderWorkflowEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("OPERATIONAL", "Operativo"),
                            ("BILLING", "Cobro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                ("comment", models.TextField(blank=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        related_name="order_workflow_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="workflow_events",
                        to="api.order",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
    ]
