# Generated by Django 5.0.2 on 2026-05-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_quotation_billing_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreightZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "name_key",
                    models.CharField(editable=False, max_length=150, unique=True),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notes", models.CharField(blank=True, max_length=220)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
