# Generated by Django 5.0.2 on 2026-06-17 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_backfill_user_profiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="assigned_driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="maps_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="order",
            name="operational_status",
            field=models.CharField(
                choices=[
                    ("PROGRAMADA", "Programada"),
                    ("EN_CAMINO", "En camino"),
                    ("ENTREGADO", "Entregado"),
                    ("POR_RECOGER", "Por recoger"),
                    ("CLIENTE_ENTREGA", "Cliente entrega"),
                    ("RECOGIDO", "Recogido"),
                ],
                default="PROGRAMADA",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderworkflowevent",
            name="category",
            field=models.CharField(
                choices=[
                    ("OPERATIONAL", "Operativo"),
                    ("BILLING", "Cobro"),
                    ("ASSIGNMENT", "Asignación"),
                ],
                max_length=20,
            ),
        ),
    ]
