# Generated by Django 5.0.2 on 2026-06-25 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_order_assigned_driver_order_maps_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="office_closed",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="OrderExtraCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("concepto", models.CharField(max_length=220)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_costs",
                        to="api.order",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
    ]
