# Generated by Django 5.0.2 on 2026-07-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_add_client_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="printed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
