# Generated by Django 5.0.2 on 2026-09-12 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_order_printed_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderRouteConstraint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("time_window_start", models.TimeField(blank=True, null=True)),
                ("time_window_end", models.TimeField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("ALTA", "Alta"),
                            ("NORMAL", "Normal"),
                            ("BAJA", "Baja"),
                        ],
                        default="NORMAL",
                        max_length=10,
                    ),
                ),
                ("raw_note", models.TextField(blank=True)),
                ("parsed_by_ai", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="route_constraints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_constraint",
                        to="api.order",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RouteOptimizationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("route_date", models.DateField()),
                ("recommended_departure", models.TimeField(blank=True, null=True)),
                ("first_stop_eta", models.TimeField(blank=True, null=True)),
                ("total_duration_minutes", models.PositiveIntegerField(default=0)),
                (
                    "total_distance_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("stops", models.JSONField(blank=True, default=list)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_optimization_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="routeoptimizationrun",
            constraint=models.UniqueConstraint(
                fields=("driver", "route_date"),
                name="unique_route_optimization_per_driver_day",
            ),
        ),
    ]
