# Generated by Django 5.0.2 on 2026-09-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_orderrouteconstraint_routeoptimizationrun_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryproduct",
            name="category",
            field=models.CharField(
                choices=[
                    ("VAJILLA", "Vajilla"),
                    ("MOBILIARIO", "Mobiliario"),
                    ("OTROS", "Otros"),
                ],
                default="OTROS",
                max_length=20,
            ),
        ),
    ]
