# Generated by Django 5.0.2 on 2026-09-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_inventoryproduct_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryproduct",
            name="category",
            field=models.CharField(
                choices=[
                    ("VAJILLA", "Vajilla"),
                    ("MOBILIARIO", "Mobiliario"),
                    ("MANTELERIA", "Mantelería"),
                    ("CARPAS", "Carpas"),
                    ("OTROS", "Otros"),
                ],
                default="OTROS",
                max_length=20,
            ),
        ),
    ]
