# Generated by Django 5.0.2 on 2026-09-17 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_inventoryproduct_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotationitem",
            name="inventory_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotation_items",
                to="api.inventoryproduct",
            ),
        ),
    ]
