# Generated by Django 5.2.17 on 2026-09-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_quotationitem_inventory_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityRateBucket",
            fields=[
                (
                    "key",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
        ),
    ]
