from django.urls import path

from .views import (
    AccountingOverviewView,
    ClientAddressDetailView,
    ClientAddressListCreateView,
    ClientDetailView,
    ClientListView,
    CurrentSessionView,
    DashboardOverviewView,
    DriverRouteView,
    FreightZoneDetailView,
    FreightZoneListCreateView,
    HealthCheckView,
    InventoryDetailView,
    InventoryListCreateView,
    LoginView,
    LogoutView,
    OrderArchiveListView,
    OrderAssignmentView,
    OrderBulkStatusUpdateView,
    OrderCancelView,
    OrderCloseRegistroView,
    OrderDetailView,
    OrderExcelExportView,
    OrderExtraCostDeleteView,
    OrderExtraCostsView,
    OrderFolioOptionsView,
    OrderImportView,
    OrderListCreateView,
    OrderPdfExportView,
    OrderPrintStatusView,
    OrderRenameView,
    OrderStatusUpdateView,
    QuotationConfirmView,
    QuotationDetailView,
    QuotationExcelExportView,
    QuotationListCreateView,
    QuotationPdfExportView,
    RegisterView,
    TeamMemberDetailView,
    TeamMemberListCreateView,
)

urlpatterns = [
    path("health/", HealthCheckView.as_view(), name="health-check"),
    path("auth/login/", LoginView.as_view(), name="api-login"),
    path("auth/register/", RegisterView.as_view(), name="api-register"),
    path("auth/me/", CurrentSessionView.as_view(), name="api-me"),
    path("auth/logout/", LogoutView.as_view(), name="api-logout"),
    path("team/", TeamMemberListCreateView.as_view(), name="team-list"),
    path("team/<int:user_id>/", TeamMemberDetailView.as_view(), name="team-detail"),
    path("clients/", ClientListView.as_view(), name="client-list"),
    path("clients/<str:client_id>/", ClientDetailView.as_view(), name="client-detail"),
    path("clients/<str:client_id>/addresses/", ClientAddressListCreateView.as_view(), name="client-address-list"),
    path("clients/<str:client_id>/addresses/<int:addr_id>/", ClientAddressDetailView.as_view(), name="client-address-detail"),
    path("inventory/", InventoryListCreateView.as_view(), name="inventory-list"),
    path("inventory/<int:product_id>/", InventoryDetailView.as_view(), name="inventory-detail"),
    path("quotations/", QuotationListCreateView.as_view(), name="quotation-list"),
    path(
        "quotations/<str:quotation_id>/",
        QuotationDetailView.as_view(),
        name="quotation-detail",
    ),
    path(
        "quotations/<str:quotation_id>/export/xls/",
        QuotationExcelExportView.as_view(),
        name="quotation-export-xls",
    ),
    path(
        "quotations/<str:quotation_id>/export/excel/",
        QuotationExcelExportView.as_view(),
        name="quotation-export-excel",
    ),
    path(
        "quotations/<str:quotation_id>/export/pdf/",
        QuotationPdfExportView.as_view(),
        name="quotation-export-pdf",
    ),
    path(
        "quotations/<str:quotation_id>/confirm/",
        QuotationConfirmView.as_view(),
        name="quotation-confirm",
    ),
    path("orders/", OrderListCreateView.as_view(), name="order-list"),
    path("orders/folio-options/", OrderFolioOptionsView.as_view(), name="order-folio-options"),
    path("orders/import/", OrderImportView.as_view(), name="order-import"),
    path("orders/my-route/", DriverRouteView.as_view(), name="order-my-route"),
    path("orders/archive/", OrderArchiveListView.as_view(), name="order-archive-list"),
    path("orders/bulk-update-status/", OrderBulkStatusUpdateView.as_view(), name="order-bulk-status-update"),
    path("orders/<str:order_id>/status/", OrderStatusUpdateView.as_view(), name="order-status-update"),
    path("orders/<str:order_id>/export/xls/", OrderExcelExportView.as_view(), name="order-export-xls"),
    path("orders/<str:order_id>/export/excel/", OrderExcelExportView.as_view(), name="order-export-excel"),
    path("orders/<str:order_id>/export/pdf/", OrderPdfExportView.as_view(), name="order-export-pdf"),
    path("orders/<str:order_id>/rename/", OrderRenameView.as_view(), name="order-rename"),
    path("orders/<str:order_id>/cancel/", OrderCancelView.as_view(), name="order-cancel"),
    path("orders/<str:order_id>/print-status/", OrderPrintStatusView.as_view(), name="order-print-status"),
    path("orders/<str:order_id>/assign/", OrderAssignmentView.as_view(), name="order-assign"),
    path("orders/<str:order_id>/costs/", OrderExtraCostsView.as_view(), name="order-costs"),
    path("orders/<str:order_id>/costs/<int:cost_id>/", OrderExtraCostDeleteView.as_view(), name="order-cost-delete"),
    path("orders/<str:order_id>/close-registro/", OrderCloseRegistroView.as_view(), name="order-close-registro"),
    path("orders/<str:order_id>/", OrderDetailView.as_view(), name="order-detail"),
    path("dashboard/overview/", DashboardOverviewView.as_view(), name="dashboard-overview"),
    path("accounting/overview/", AccountingOverviewView.as_view(), name="accounting-overview"),
    path("freight-zones/", FreightZoneListCreateView.as_view(), name="freight-zone-list"),
    path("freight-zones/<int:zone_id>/", FreightZoneDetailView.as_view(), name="freight-zone-detail"),
]
